// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package ticker

import (
	"sync"
	"time"
)

// Ensure, that TickerMock does implement Ticker.
// If this is not the case, regenerate this file with moq.
var _ Ticker = &TickerMock{}

// TickerMock is a mock implementation of Ticker.
//
// 	func TestSomethingThatUsesTicker(t *testing.T) {
//
// 		// make and configure a mocked Ticker
// 		mockedTicker := &TickerMock{
// 			InitFunc: func() <-chan time.Time {
// 				panic("mock out the Init method")
// 			},
// 		}
//
// 		// use mockedTicker in code that requires Ticker
// 		// and then make assertions.
//
// 	}
type TickerMock struct {
	// InitFunc mocks the Init method.
	InitFunc func() <-chan time.Time

	// calls tracks calls to the methods.
	calls struct {
		// Init holds details about calls to the Init method.
		Init []struct {
		}
	}
	lockInit sync.RWMutex
}

// Init calls InitFunc.
func (mock *TickerMock) Init() <-chan time.Time {
	if mock.InitFunc == nil {
		panic("TickerMock.InitFunc: method is nil but Ticker.Init was just called")
	}
	callInfo := struct {
	}{}
	mock.lockInit.Lock()
	mock.calls.Init = append(mock.calls.Init, callInfo)
	mock.lockInit.Unlock()
	return mock.InitFunc()
}

// InitCalls gets all the calls that were made to Init.
// Check the length with:
//     len(mockedTicker.InitCalls())
func (mock *TickerMock) InitCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockInit.RLock()
	calls = mock.calls.Init
	mock.lockInit.RUnlock()
	return calls
}
